package db

import (
	"database/sql"
	"fmt"
	_ "github.com/lib/pq"
	"log"
)

type Database struct {
	db *sql.DB
}

var bd *Database

// Public

// New создает структуру Database и возвращает указатель на нее
func New() *Database {
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s "+
		"password=%s dbname=%s sslmode=disable",
		"db", 5432, "postgres-dev", "user", "dev")
	db, err := sql.Open("postgres", psqlInfo)
	if err != nil {
		log.Fatal(err)
	}
	bd := &Database{db, }
	return bd
}

// Initialize инициализация БД. Создание таблиц. timezones - список допустимых временных зон
func (d Database) Initialize(timezones []string) {
	err := d.db.Ping()
	if err != nil {
		log.Fatal(err)
	}
	d.dropTables()
	d.createTUsers()
	d.createTTimezones(timezones)
	d.createTUserData()
}

// GetTimezones возвращает срез зон, которые пользователь userID уже запрашивал
func (d Database) GetTimezones(userID int) []string {
	query := "select timezone from user_data where user_id = $1"
	rows, err := d.db.Query(query, userID)
	if err != nil {
		log.Printf("db gettimezones: %v", err)
		return nil
	}
	defer rows.Close()

	result := make([]string, 0)
	for rows.Next() {
		var timezone string
		if err := rows.Scan(&timezone); err != nil {
			log.Printf("db gettimezones: %v", err)
			return nil
		}
		result = append(result, timezone)
	}
	return result
}

// CreateUser возвращает false, если пользователь с id уже существует
// CreateUser возвращает true, если пользователь с id был создан
func (d Database) CreateUser(id int) bool {
	query := "select * from users where id = $1"
	row := d.db.QueryRow(query, id)
	var tmp int
	if err := row.Scan(&tmp); err == sql.ErrNoRows {
		fmt.Println(err)
		query = "insert into users(id) values ($1)"
		_, err := d.db.Exec(query, id)
		if err != nil {
			log.Println(err)
		}
		return true
	}
	fmt.Println("уже есть")
	return false
}

// UpdateUserData если пользователь с id не существет, то создает его и записывает timezones в таблицу user_data
// UpdateUserData если пользователь с id существует, то обновлет принадлежащие ему записи в таблице user_data:
// UpdateUserData дописывает новые временные зоны
func (d Database) UpdateUserData(id int, timezones []string) {
	ext := d.CreateUser(id)
	fmt.Printf("МЫ были ТУТ")
	if ext {
		query := "insert into user_data (user_id, timezone) values ($1, $2)"
		for i := 0; i < len(timezones); i++ {
			_, err := d.db.Exec(query, id, timezones[i])
			if err != nil {
				log.Printf("db updateuserdata: %v", err)
			}
		}
	} else {
		tmpSlice := d.GetTimezones(id)

		union := make(map[string]bool)
		for _, str := range tmpSlice {
			union[str] = true
		}
		for _, str := range timezones {
			union[str] = true
		}
		// duplicate key violation
		query := "insert into user_data (user_id, timezone) values ($1, $2)"
		for k := range union {
			_, err := d.db.Exec(query, id, k)
			if err != nil {
				log.Printf("db updateuserdata: %v", err)
			}
		}
	}
}

// Close закрывает подключение к базе данных
func (d Database) Close() {
	err := d.db.Close()
	if err != nil {
		log.Printf("db close: %v", err)
	}
}

// Private

// dropTables удаляет таблицы timezones, users и user_data, если они существуют
func (d Database) dropTables() {
	query := "drop table if exists %s"
	tables := []string{
		"user_data",
		"users",
		"timezones",
	}
	for i := 0; i < len(tables); i++ {
		_, err := d.db.Exec(fmt.Sprintf(query, tables[i]))
		if err != nil {
			log.Fatal(err)
		}
	}
}

// createTUsers создает таблицу users
func (d Database) createTUsers() {
	// Создание таблиц
	// Таблица users
	query := `create table users(
  				id integer PRIMARY KEY,
  				timestamp timestamp default current_timestamp
			 );`
	_, err := d.db.Exec(query)
	if err != nil {
		log.Fatal(err)
	}
}

// createTTimezones создает таблицу timezones, записывает в нее зоны и среза timezones
func (d Database) createTTimezones(timezones []string) {
	// Таблица timezones
	query := `create table timezones(
  				id integer generated by default as identity PRIMARY KEY,
  				timezone varchar(30) NOT NULL UNIQUE
			 );`
	_, err := d.db.Exec(query)
	if err != nil {
		log.Fatal(err)
	}
	// инициализация timezones
	query = "insert into timezones (timezone) values ($1)"
	for i := 0; i < len(timezones); i++ {
		_, err = d.db.Exec(query, timezones[i])
	}
}

// createTUserData создает таблицу user_data
func (d Database) createTUserData() {
	// таблица user_data
	query := `create table user_data(
  				user_id integer,
  				timezone varchar(30) NOT NULL,
  				timestamp timestamp default current_timestamp,
 				PRIMARY KEY(user_id, timezone),
  				FOREIGN KEY (user_id) references users(id),
  				FOREIGN KEY (timezone) REFERENCES timezones(timezone)
			  );`
	_, err := d.db.Exec(query)
	if err != nil {
		log.Fatal(err)
	}
}
